// v5.42 EXPECTED FIGURES — generated by the SAME oracle that will be the test's oracle
// (hand_86.mjs::statute86, transcribed from 26 U.S.C. Sec.86). Deliberately NOT a second
// independent script: at v5.41 the expectations came from a separate derivation that had
// drifted from the code's own scope (an out-of-scope dividend term and an undecided
// allocation rule), and the brief's table shipped wrong twice over. One oracle, used for
// both the expectation and the assertion, cannot drift from itself.
//
// The ladder recursion below is transcribed from v5.41 src L8830-8900 and is UNCHANGED by
// v5.42 — only taxableSS moves. TOOLING. Asserts nothing. Counted in NO check total.
import { statute86 } from "./hand_86.mjs";

const G = 0.045, ULT = { 75: 24.6, 76: 23.7 };
const A0 = 1180000, B0 = 218600;                 // retireStartBalances(2029).tradInitA/B
const PEN = 4800, SSA = 39600, SSB = 15600;      // getPension()*12, getSSA()*12, getSSB()*12
const SSA_YR = 2031;                             // spouse A claims 2031; B already claiming
const dobA = 1964, dobB = 1966, START = 2029, END = 2040, endA = 2038, endB = 2040;
const taper = y => (y === 2029 ? 20000 : y === 2030 ? 18000 : y === 2031 ? 15000 : 0);
const usd = n => "$" + Math.round(n).toLocaleString();
const K = n => "$" + Math.round(n / 1000) + "K";

// The shipped (pre-fix) upper tier: a cliff straight to 85%.
function cliff86(ss, nonSS) {
  const prov = nonSS + ss * 0.5, T1 = 32000, T2 = 44000;
  if (prov > T2) return Math.round(ss * 0.85);
  if (prov > T1) return Math.round(Math.min((prov - T1) * 0.5, ss * 0.85));
  return 0;
}

function ladder(rothAmount) {
  let a = A0, b = B0; const out = [];
  for (let y = START; y <= END; y++) {
    const ageA = y - dobA, ageB = y - dobB;
    const rA = ageA >= 75 ? a / (ULT[ageA] || 6.4) : 0;      // prior 31 Dec basis
    const rB = ageB >= 75 ? b / (ULT[ageB] || 6.4) : 0;
    const rmd = Math.round(rA + rB);
    const gA = a * (1 + G), gB = b * (1 + G);
    const capA = Math.max(0, (y <= endA ? gA : 0) - rA);
    const capB = Math.max(0, (y <= endB ? gB : 0) - rB);
    const conv = Math.min(rothAmount, capA + capB);
    const cA = (capA + capB) > 0 ? conv * (capA / (capA + capB)) : 0;
    a = Math.max(0, gA - cA - rA); b = Math.max(0, gB - (conv - cA) - rB);

    const ss = (y >= SSA_YR ? SSA : 0) + SSB;
    const work = taper(y);
    const nonSS = PEN + work + conv + rmd;
    const tOld = cliff86(ss, nonSS), tNew = Math.round(statute86(ss, nonSS, true));
    out.push({
      y, conv: Math.round(conv), rmd, ss, prov: nonSS + ss * 0.5,
      tOld, tNew,
      magiOld: PEN + work + tOld + conv + rmd,
      magiNew: PEN + work + tNew + conv + rmd,
    });
  }
  return out;
}

const POSITIONS = [70000, 50000, 30000, 20000, 15000, 10000];
for (const p of POSITIONS) {
  const rows = ladder(p);
  const moved = rows.filter(r => r.magiOld !== r.magiNew);
  console.log(`\n═══ SLIDER $${p.toLocaleString()} ═══  ${moved.length ? moved.length + " of 12 years move" : "NO YEAR MOVES — the fix is invisible here"}`);
  console.log("year  prov      taxableSS old →  new     MAGI old   → new        Δ        rendered");
  for (const r of rows) {
    const d = r.magiNew - r.magiOld;
    console.log(
      `${r.y}  ${String(Math.round(r.prov)).padStart(8)}  ${usd(r.tOld).padStart(8)} → ${usd(r.tNew).padStart(8)}  ` +
      `${usd(r.magiOld).padStart(9)} → ${usd(r.magiNew).padStart(9)}  ${(d ? usd(d) : "—").padStart(9)}  ` +
      `${K(r.magiOld)} → ${K(r.magiNew)}`);
  }
}
console.log("\nNOTE: at the $70,000 DEFAULT the fix changes nothing — every existing t23 pin stays green.");
